name: Java CI

on: 
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build
