name: Nightly Build
on:
  push:
    branches:
      - master
      - develop
      - restructurization

jobs:
  build:
    name: Build SpinyGUI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        version: 12
    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        sonarLogin: ${{secrets.SONAR_TOKEN}}
        JAVA_OPTS: -Xmx4096m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=512m
      run: ./gradlew clean build test sonarqube
#  sonarCloudTrigger:
#    name: SonarCloud Verification
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - name: SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}