name: Nightly Build
on: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java Action
      uses: actions/setup-java@v1.0.0
      with:
        version: 12
    - name: Build with Gradle
      env:
        sonarLogin: ${{secrets.SONAR_TOKEN}}
      run: ./gradlew clean build test sonarqube
